const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    getStats: (save) => ipcRenderer.invoke('getStats', save),
    saveNameAndDesc: (name, description, save) => ipcRenderer.send('saveNameAndDesc', name, description, save),
    logToMain: (text) => ipcRenderer.send('logToMain', text),
    openFolder: () => ipcRenderer.send('openFolder'),
    deleteSave: (save) => { ipcRenderer.send('deleteSave', save) },
    changeDCState: (state, message) => { ipcRenderer.send('changeDCState', state, message) },
    checkForSaves: (index) => ipcRenderer.invoke('checkForSaves', index),
    exitGame: () => ipcRenderer.send('exitGame'),
    saveGame: (worlds, playerData, save, meta, stats, settings, droppedItems) => ipcRenderer.send('saveGame', worlds, playerData, save, meta, stats, settings, droppedItems),
    getWorldData: (save) => ipcRenderer.invoke('getWorldData', save),
    onData: (callback) => ipcRenderer.on('data', (event, data) => callback(data)),
    openLink: (url) => { ipcRenderer.send('openLink', url) },
    saveSettings: (settings, values) => ipcRenderer.send('saveSettings', settings, values),
    fetchSettings: () => ipcRenderer.invoke('fetchSettings'),
    fetchGlobalStats: () => ipcRenderer.invoke('fetchGlobalStats'),
    fetchAchievements: () => ipcRenderer.invoke('fetchAchievements'),
    getConfigs: () => ipcRenderer.invoke('getConfigs'),
    grantAchievement: (achievement) => ipcRenderer.send('grantAchievement', achievement),
    resetConfigs: () => ipcRenderer.send('resetConfigs'),
    connectToDevice: () => ipcRenderer.invoke('connectToDevice'),
    disconnentFromDevice: () => ipcRenderer.invoke('disconnentFromDevice'),
    onArduinoData: (cb) => ipcRenderer.on('arduinoData', (_, data) => cb(data)),
    sendMSGToDevice: (msg) => ipcRenderer.send('sendMSGToDevice', msg),
    postStats: (url) => ipcRenderer.invoke('postStats', url),
    fetchSkins: () => ipcRenderer.invoke('fetchSkins'),
    rename: (username) => ipcRenderer.send('rename', username),
    fetchName: () => ipcRenderer.invoke('fetchName'),
    selectSkin: (index) => ipcRenderer.send('selectSkin', index),
    checkCode: (code) => ipcRenderer.send('checkCode', code)
});
